import { InferSchemaType, Schema, model } from "mongoose";

const userSchema = new Schema(
  {
    _id: {
      // ID generated by Google Oauth, must be called _id to be queried with .findById()
      type: String,
    },
    email: {
      type: String,
      required: true,
    },
    //Pass in from google
    firstName: {
      type: String,
      required: true,
    },
    lastName: {
      type: String,
      required: true,
    },
    isAlumni: {
      type: Boolean,
      default: false,
    },
    //this is what im doing
    linkedIn: {
      type: String,
    },
    phoneNumber: {
      type: String,
    },
    //Only for students
    major: {
      type: String,
    },
    //Only for students
    classLevel: {
      type: String,
    },
    //Only for alumni
    company: {
      type: Object,
    },
    //
    shareProfile: {
      type: Boolean,
    },
  },
  {
    // Automatically generates created and updated times
    timestamps: true,
  },
);

type User = InferSchemaType<typeof userSchema>;

export default model<User>("User", userSchema);
